name: TestSuchi-deployment

releases:
- name: hello-world
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: server
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: hello-world
    templates:
    - name: hello-world
      release: hello-world

#bosh -d TestSuchi-deployment deploy manifest.yml

#bosh -d TestSuchi-deployment errands

#bosh -d TestSuchi-deployment run-errand hello-world
